"""add user login

Revision ID: 5e22b1d0d85b
Revises: 3d10344167d7
Create Date: 2026-08-06 20:51:20.470115
"""
from alembic import op
import sqlalchemy as sa


revision = '5e22b1d0d85b'
down_revision = '3d10344167d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
